/**
 * WINE PAIRING ENGINE
 * ====================
 *
 * Loads pre-computed pairing data from pairings.json (generated by
 * scripts/generate-pairings.py) and displays per-dish suggestions
 * in a modal popup.
 *
 * Architecture:
 *   data/menus/<ACTIVE_MENU>/pairings.json  → loaded on page load
 *   openPairing(dishId, dishName)           → called from HTML onclick
 *   Modal shows top 3 candidates for the dish, score in grapes
 *
 * To change the active menu, update ACTIVE_MENU below.
 */

const ACTIVE_MENU = 'nanban-kaiseki';

// ============================================================================
// DATA LOADING
// ============================================================================

let pairingsData = null;

async function loadPairingData() {
    const url = `data/menus/${ACTIVE_MENU}/pairings.json`;
    try {
        const response = await fetch(url);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        pairingsData = await response.json();
        console.log('Pairing data loaded:', ACTIVE_MENU,
            '—', Object.keys(pairingsData.per_dish || {}).length, 'dishes');
    } catch (err) {
        console.error('Error loading pairing data:', err);
        pairingsData = null;
    }
}

// ============================================================================
// PAIRING LOOKUP
// ============================================================================

/**
 * Get top N per-dish candidates from pairings.json.
 * Returns empty array if data not loaded or dish not found.
 */
function getPairingsForDish(dishId, n = 3) {
    if (!pairingsData || !pairingsData.per_dish) return [];
    const candidates = pairingsData.per_dish[dishId];
    if (!candidates || candidates.length === 0) {
        console.warn('No pairings for dish:', dishId);
        return [];
    }
    return candidates.slice(0, n);
}

// ============================================================================
// DISPLAY HELPERS
// ============================================================================


function formatPrice(eur) {
    if (eur == null) return '—';
    return `€${eur.toFixed(2)}`;
}

function formatType(type) {
    const types = {
        white: 'Branco', red: 'Tinto', rosé: 'Rosé',
        sparkling: 'Espumante', fortified: 'Licoroso'
    };
    return types[type] || type || '';
}

// ============================================================================
// CARD RENDERING
// ============================================================================

function buildWineCard(w) {
    const price  = formatPrice(w.carta_price ?? w.price_eur);
    const type   = formatType(w.type);
    const region = w.doc || w.region || '';

    return `
        <div class="pairing-card">
            <h3 class="wine-name">${w.name}</h3>
            <p class="wine-meta">${w.producer}</p>
            <p class="wine-details">${type}${region ? ' · ' + region : ''}${price !== '—' ? ' · ' + price : ''}</p>
        </div>
    `;
}

function buildPairingHTML(dishName, pairings) {
    if (!pairings || pairings.length === 0) {
        return `
            <h2 class="pairing-modal-title">Harmonizações</h2>
            <p class="no-pairings">Nenhuma sugestão disponível para este prato.</p>
        `;
    }

    const cards = pairings.map(buildWineCard).join('');

    return `
        <h2 class="pairing-modal-title">${dishName}</h2>
        <div class="pairings-container">
            ${cards}
        </div>
    `;
}

// ============================================================================
// MODAL CONTROL
// ============================================================================

function showPairingPopup(dishId, dishName) {
    const pairings = getPairingsForDish(dishId, 10);
    const html     = buildPairingHTML(dishName, pairings);

    const modal   = document.getElementById('pairingModal');
    const content = modal.querySelector('.pairing-modal-content');

    content.innerHTML = html;
    modal.classList.add('active');
}

function closePairingPopup() {
    const modal = document.getElementById('pairingModal');
    if (modal) modal.classList.remove('active');
}

// ============================================================================
// EVENT HANDLERS
// ============================================================================

/**
 * Global entry point — called from onclick in booklet-page-menu HTML.
 * Prevents the click from bubbling to the page-flip handler.
 */
window.openPairing = function(dishId, dishName, event) {
    if (event) event.stopPropagation();
    showPairingPopup(dishId, dishName);
};

function setupPairingModal() {
    const modal = document.getElementById('pairingModal');
    if (!modal) {
        console.warn('pairingModal element not found — pairing system disabled');
        return;
    }

    const closeBtn = modal.querySelector('.pairing-modal-close');
    if (closeBtn) closeBtn.onclick = closePairingPopup;

    // Close on background click (not on card click)
    modal.onclick = function(e) {
        if (e.target === modal) closePairingPopup();
    };

    // Close on ESC
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && modal.classList.contains('active')) {
            closePairingPopup();
        }
    });
}

// ============================================================================
// SEE MORE EXPAND
// ============================================================================


// ============================================================================
// PAIRING PAGE RENDERING (kaiseki + pack-a + pack-b)
// ============================================================================

// Set a price to show at the bottom of the kaiseki page.
// Example: const KAISEKI_PAIRING_PRICE = { amount: '€65', detail: 'por pessoa · menu completo' };
const KAISEKI_PAIRING_PRICE = null;

function buildKaisekiRow(entry) {
    const w = entry.wine;
    return `
        <div class="kaiseki-row">
            <span class="kaiseki-course">${entry.dish_name}</span>
            <span class="kaiseki-wine">${w.name}</span>
        </div>
    `;
}

function buildPackWineCard(w) {
    const price = (w.carta_price ?? w.price_eur) != null ? `€${(w.carta_price ?? w.price_eur).toFixed(2)}` : '—';
    return `
        <div class="pack-wine">
            <div class="pack-wine-row">
                <div class="pack-wine-left">
                    <span class="pack-arc">${w.arc_label || ''}</span>
                    <span class="pack-name">${w.name}</span>
                    <span class="pack-producer">${w.producer} · ${w.doc || w.region || ''}</span>
                </div>
                <div class="pack-wine-right">
                    <span class="pack-price">${price}</span>
                </div>
            </div>
        </div>
    `;
}

function renderPackPage(packKey) {
    // packKey uses underscores (matches pairings.json): 'pack_a', 'pack_b'
    // element IDs use hyphens (matches HTML): 'pack-a-*', 'pack-b-*'
    const elemId  = packKey.replace(/_/g, '-');
    const packData = pairingsData.pack_pairings && pairingsData.pack_pairings[packKey];
    if (!packData) return;

    const labelEl   = document.getElementById(elemId + '-label');
    const taglineEl = document.getElementById(elemId + '-tagline');
    const winesEl   = document.getElementById(elemId + '-wines');

    if (labelEl)   labelEl.textContent  = packData.label   || '';
    if (taglineEl) taglineEl.textContent = packData.tagline || '';
    if (winesEl)   winesEl.innerHTML    = (packData.wines || []).map(buildPackWineCard).join('');
}

function renderPairingPage() {
    // Retry until all DOM elements are present (race with async page injection)
    const kaisekiEl  = document.getElementById('kaiseki-rows');
    const kaiseki2El = document.getElementById('kaiseki-rows-2');
    const packAEl    = document.getElementById('pack-a-wines');
    const packBEl    = document.getElementById('pack-b-wines');
    if (!kaisekiEl || !kaiseki2El || !packAEl || !packBEl) {
        renderPairingPage._attempts = (renderPairingPage._attempts || 0) + 1;
        if (renderPairingPage._attempts < 20) setTimeout(renderPairingPage, 200);
        return;
    }
    renderPairingPage._attempts = 0;
    if (!pairingsData) return;

    // Kaiseki page 1: courses 1–5 (indices 0–4)
    const kaiseki = pairingsData.sequence_pairing || [];
    kaisekiEl.innerHTML  = kaiseki.slice(0, 5).map(buildKaisekiRow).join('');

    // Kaiseki page 2: courses 6–10 (indices 5–9) + optional price bar
    kaiseki2El.innerHTML = kaiseki.slice(5).map(buildKaisekiRow).join('');
    const priceBar = document.getElementById('kaiseki-price-bar');
    if (priceBar && KAISEKI_PAIRING_PRICE) {
        priceBar.style.display = 'flex';
        priceBar.innerHTML = `
            <span class="price-bar-label">Harmonização Kaiseki</span>
            <span>
                <span class="price-bar-amount">${KAISEKI_PAIRING_PRICE.amount}</span>
                <span class="price-bar-detail"> · ${KAISEKI_PAIRING_PRICE.detail}</span>
            </span>
        `;
    }

    // Pack pages — keys use underscores to match pairings.json
    renderPackPage('pack_a');
    renderPackPage('pack_b');
}

// ============================================================================
// INITIALIZATION
// ============================================================================

async function initializePairingSystem() {
    await loadPairingData();
    setupPairingModal();
    renderPairingPage();
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initializePairingSystem);
} else {
    initializePairingSystem();
}
